"""add schedule_id and scheduled_time to nutrition_intake

Revision ID: 1f734605413a
Revises: 4a6263312478
Create Date: 2026-01-20 07:58:28.207773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f734605413a'
down_revision: Union[str, None] = '4a6263312478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Keeping completed_by column in care_task_log for backwards compatibility
    # op.drop_column('care_task_log', 'completed_by')
    op.add_column('nutrition_intake', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.add_column('nutrition_intake', sa.Column('scheduled_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_foreign_key('fk_nutrition_intake_schedule_id', 'nutrition_intake', 'nutrition_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_nutrition_intake_schedule_id', 'nutrition_intake', type_='foreignkey')
    op.drop_column('nutrition_intake', 'scheduled_time')
    op.drop_column('nutrition_intake', 'schedule_id')
    # Note: Not re-adding completed_by as we didn't drop it
    # op.add_column('care_task_log', sa.Column('completed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
