"""add_implant_tracking

Revision ID: 43ae558a4aa6
Revises: 0c523cc887c8
Create Date: 2026-01-23 07:52:13.206509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ae558a4aa6'
down_revision: Union[str, None] = '0c523cc887c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('implant_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('body_location', sa.String(length=100), nullable=False),
    sa.Column('body_side', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('implant_date', sa.Date(), nullable=True),
    sa.Column('last_change_date', sa.Date(), nullable=True),
    sa.Column('next_change_date', sa.Date(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('implanting_provider_id', sa.Integer(), nullable=True),
    sa.Column('managing_provider_id', sa.Integer(), nullable=True),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('facility_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('mri_safe', sa.String(length=50), nullable=True),
    sa.Column('mri_notes', sa.Text(), nullable=True),
    sa.Column('is_life_sustaining', sa.Boolean(), nullable=True),
    sa.Column('requires_regular_change', sa.Boolean(), nullable=True),
    sa.Column('change_frequency_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['implanting_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['managing_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implant_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('implant_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('was_changed', sa.Boolean(), nullable=True),
    sa.Column('old_serial_number', sa.String(length=255), nullable=True),
    sa.Column('new_serial_number', sa.String(length=255), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['implant_id'], ['implants.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('implant_notes')
    op.drop_table('implants')
    # ### end Alembic commands ###
