"""add nutrition goals outputs and schedules tables

Revision ID: 4a6263312478
Revises: 63158b364c7a
Create Date: 2026-01-20 05:44:36.575102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6263312478'
down_revision: Union[str, None] = '63158b364c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('water_ml_target', sa.Float(), nullable=True),
    sa.Column('total_fluid_ml_target', sa.Float(), nullable=True),
    sa.Column('calories_target', sa.Float(), nullable=True),
    sa.Column('calories_min', sa.Float(), nullable=True),
    sa.Column('calories_max', sa.Float(), nullable=True),
    sa.Column('protein_grams_target', sa.Float(), nullable=True),
    sa.Column('carbs_grams_target', sa.Float(), nullable=True),
    sa.Column('fat_grams_target', sa.Float(), nullable=True),
    sa.Column('fiber_grams_target', sa.Float(), nullable=True),
    sa.Column('sodium_mg_max', sa.Float(), nullable=True),
    sa.Column('sugar_grams_max', sa.Float(), nullable=True),
    sa.Column('potassium_mg_max', sa.Float(), nullable=True),
    sa.Column('phosphorus_mg_max', sa.Float(), nullable=True),
    sa.Column('urine_output_ml_min', sa.Float(), nullable=True),
    sa.Column('bowel_movements_target', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('default_item_name', sa.String(length=200), nullable=True),
    sa.Column('default_amount', sa.Float(), nullable=True),
    sa.Column('default_amount_unit', sa.String(length=50), nullable=True),
    sa.Column('default_calories', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_care_task', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('care_task_log_id', sa.Integer(), nullable=True),
    sa.Column('output_type', sa.String(length=50), nullable=False),
    sa.Column('consistency', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_unit', sa.String(length=20), nullable=True),
    sa.Column('clarity', sa.String(length=50), nullable=True),
    sa.Column('is_diaper', sa.Boolean(), nullable=False),
    sa.Column('diaper_wetness', sa.String(length=20), nullable=True),
    sa.Column('diaper_soiled', sa.Boolean(), nullable=True),
    sa.Column('is_catheter', sa.Boolean(), nullable=False),
    sa.Column('catheter_bag_emptied', sa.Boolean(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('has_blood', sa.Boolean(), nullable=False),
    sa.Column('has_mucus', sa.Boolean(), nullable=False),
    sa.Column('pain_reported', sa.Boolean(), nullable=False),
    sa.Column('straining', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_task_log_id'], ['care_task_log.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # Commented out - unrelated column change
    # op.drop_column('care_task_log', 'completed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('care_task_log', sa.Column('completed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('nutrition_outputs')
    op.drop_table('nutrition_schedules')
    op.drop_table('nutrition_goals')
    # ### end Alembic commands ###
